exclude_paths:
  # ignore undocumented test cases, etc
  - '**/src/test/**'
  # ignore unused parameters, constant conditions, etc
  - 'etc/fake-bindings/**'
  # ignore undocumented public declarations in samples
  - 'samples/android-sample/**'
  - 'samples/fx-sample/**'
  - 'samples/logic-sample/**'
